services:
  postgres:
    image: postgres:16.3
    container_name: backend-challenge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_challenge
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-challenge-api
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_challenge
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./scripts:/usr/src/app/scripts
    command: npm run dev

volumes:
  postgres_data:
